### ISSUE TITLE
[bug] MGA Solver

### ISSUE THREAD

**Issue by samgdotson** [TemoaProject/temoa#21]
When trying to run an uncertainty analysis with MGA, the following error message is returned:

```bash
$ sqlite3 data_files/cost.sqlite < data_files/UIUC_2050_cost.sql
$ yes | python $TEMOA/temoa_model/ --config=data_files/run_costmga.txt 

Continue Operation? [Press enter to continue or CTRL+C to abort]

Solver will write file: cost2050.lp

[    0.15] Reading data files.
[        ] Creating Temoa model instance.Warning: ('uiuc', 'IMPELC', 2000) has a specified Efficiency, but does not have any existing install base (ExistingCapacity).
[    5.52]
name 'M' is not defined
Exiting Temoa ...
Traceback (most recent call last):
  File "/home/dotson/research/temoa//temoa_model/temoa_run.py", line 265, in createAndSolve
    for k in self.solveWithMGA():
  File "/home/dotson/research/temoa//temoa_model/temoa_run.py", line 168, in solveWithMGA
    temoaMGAInstance.instance.ActivityByTechConstraint = Constraint(M.tech_all, rule=ActivityByTech_Constraint)
NameError: name 'M' is not defined
```

The variable ``M`` is not referenced anywhere else in ``temoa_run.py``.

#### Temoa Installation process I used

System: Ubuntu 20.04
Python: 3.7.6
Conda: 4.9.2

```bash
$ git clone git@github.com:temoaproject/temoa.git
$ cd temoa
$ conda env create
$ conda activate temoa-py3
$ echo "export TEMOA = home/dotson/research/temoa" >> ~/.bashrc
```

#### Notes:
* It looks like the July 2020 commit (2217661a5eadfa5e76e83242b34f93ac502aa424) introduced this error. Since I was able to successfully run MGA before then.
* I am able to run a single optimization scenario with Temoa, using this installation.
* I have attached the SQL (as a text file) and config files I used to run this scenario.
[run_costmga.txt](https://github.com/TemoaProject/temoa/files/6190816/run_costmga.txt)
[UIUC_2050_cost.txt](https://github.com/TemoaProject/temoa/files/6190825/UIUC_2050_cost.txt)

Edit: Adds the sqlite command.

**Comment by samgdotson** [comment]
This issue was closed by PR #22
