### ISSUE TITLE
Problems running Utopia dataset

### ISSUE THREAD

**Issue by christiancodes** [TemoaProject/temoa#26]
Hi there – having an issue running the model with the test dataset on a fresh install. 

```
$ python temoa_model/ data_files/temoa_utopia.dat 

[    0.02] Reading data files.
[    0.07] Creating Temoa model instance.
[    0.06] Solving.
[        ] Calculating reporting variables and formatting results.Exception found in solve_temoa_instance
'Namespace' object has no attribute 'scenario''Namespace' object has no attribute 'scenario'
Exiting Temoa ...
Traceback (most recent call last):
  File "temoa_model/temoa_run.py", line 275, in createAndSolve
    for k in self.solveWithoutMGA():
  File "temoa_model/temoa_run.py", line 247, in solveWithoutMGA
    for k in temoaInstance1.solve_temoa_instance():
  File "temoa_model/temoa_run.py", line 417, in solve_temoa_instance
    raise model_exc
  File "temoa_model/temoa_run.py", line 396, in solve_temoa_instance
    formatted_results = pformat_results( self.instance, self.result, self.options )
  File "temoa_model/pformat_results.py", line 378, in pformat_results
    duals = collect_result_data( Cons, con_info, epsilon=1e-9 )
  File "temoa_model/pformat_results.py", line 123, in collect_result_data
    duals.loc[:,'scenario'] = options.scenario
AttributeError: 'Namespace' object has no attribute 'scenario'
```
Any help would be appreciated! Thank you.

**Comment by TemoaProject** [comment]
Try running as follows, with the config file:

$ python temoa_model/ --config=temoa_model/config_sample

This command will solve the temoa_utopia.sqlite without an error.
